### PR TITLE
Added Home page

### PR DESCRIPTION
**Pull request by milindvishnoi**
image
image

### CODE REVIEW

**Comment by ArsalaBangash** [comment]
Prelim comments:

- [ ] Let's talk about whether we want a CenteredHero or TwoColumnHero. Both are available on Grey Software https://github.com/grey-software/grey.software/pull/38


- [ ] Let's add a Where Are We section and point to DH2014 as well as our digital communities/accounts. Inside, Let's have a large ThreeColumnGrid for our communities to put them front and center

- [ ] Let's discuss whether we want a white bg or a colored bg

**Comment by ArsalaBangash** [comment]
https://fonts.google.com/specimen/Raleway
https://fonts.google.com/specimen/Open+Sans

**Comment by hiimchrislim** [comment]
Github: https://github.com/utm-cssc
IG: https://www.instagram.com/utm.cssc/
Discord: discord.gg/h65HUjE4
Facebook: https://www.facebook.com/utmcssc/
Linktree: https://linktr.ee/utmcssc

**Comment by milindvishnoi** [comment]
Things To Update:
- [ ] Social Grid

**Review by ArsalaBangash — DISMISSED** [review]
The first working draft is ready to merge

**Pull request merged**
