### PR TITLE
Made Navbar Responsive 

### PR DESCRIPTION
**Pull request by milindvishnoi**
## Md View
image

## Sm View
image

### CODE REVIEW

**Review by hiimchrislim — CHANGES_REQUESTED** [review]
The hamburger menu looks great however, on an iPad display, it seems that the navigation is overlapping the search bar. It also slightly overlaps when you zoom into the display as well

image

Is it possible if the navigation could go right under the hamburger icon? (i.e. Shifting it a bit more to the right to be aligned with the hamburger icon)

image

image

**Comment by milindvishnoi** [comment]
## Requested Updates
image

I am showing it with the CSS Debugger so the lines you see will not appear.

**Comment by hiimchrislim** [comment]
Is it possible if the "x" could be a different color perhaps a red and also when hovering over the "x", could the cursor turn into a pointer?
image
image

**Review by hiimchrislim — CHANGES_REQUESTED** [review]
The hamburger icon is working great on different screen sizes, however I noticed that when zooming into the website (for example with 200% zoom), there seems to still be some overlapping with the links
image

**Comment by ArsalaBangash** [comment]
> Is it possible if the "x" could be a different color perhaps a red and also when hovering over the "x", could the cursor turn into a pointer?
> image
> image

Chris, these are defaults from the ``<input type="search" />`` that we can't override. I think a good solution would be to find a Better search bar component like https://vuetifyjs.com/en/components/autocompletes/

Since we may eventually be using the Calendar component from this library, we could leverage other components as well.

**Review by ArsalaBangash — APPROVED** [review]
Excellent work!

**Review by hiimchrislim — APPROVED** [review]

**Pull request merged**
