### PR TITLE
removed invalid link to janders linkedin

### LINKED ISSUE #90: 🐛 Bug: The link to janders linkedin is invalid
### Expected Behavior 🧭
I would expect the LinkedIn link for janders would take me to Jessica's LinkedIn, however, this does not exist :stuck_out_tongue:. 

### Current Behavior 🔍 
The current url links to John Anderson from San Anselmo, California.

### Steps to Reproduce 🔢 

1. Open CSSC site
2. Scroll down to the team section
2. Click on Jessica Anderson's LinkedIn url.

**Acceptance Criteria for Fix ✅**

- Removing the link

### Possible Solution 🛠️ 
Pushing a fix shortly

**Implementation Details 🧰**

- Making the LinkedIn field optional, conditional rendering for the link.

### Additional details ℹ️ 

N/A

### PR DESCRIPTION
**Pull request by krishchow**
Fixes #90

### CODE REVIEW

**Comment by krishchow** [comment]
Unrelated but noteworthy, is the initial setup/build process long for anyone else? It took me over 10 minutes to download the dependencies and build the site.

**Comment by hiimchrislim** [comment]
Great fix! (We were originally planning to use Jess' actual LinkedIn later on but then I was just told that she doesn't have one, so this fix is perfect!)

> Unrelated but noteworthy, is the initial setup/build process long for anyone else? It took me over 10 minutes to download the dependencies and build the site.

I did a fresh install on the repo and ran the development server as well as a build of the entire website and it took me around 2-3 minutes.

**Installing Dependencies (yarn run build)**
[4/4] Building fresh packages...
Done in 16.08s.

**Running Dev Server (yarn run dev)**
√ Client
  Compiled successfully in 27.05s
√ Server
  Compiled successfully in 15.81s

**Website Build (yarn run build)**
Done in 71.56s.

**Website Generate (yarn run generate) (Both building and exporting)**

Hash: 57583163ff6b967cc079
Version: webpack 4.44.2
Time: 43056ms
Built at: 11/24/2020 3:36:00 PM

√ Client-side fallback created: 200.html
Done in 159.19s.

I do remember the build's taking quite a while to deploy on Netlify (I believe we were using yarn generate) but now we're using nuxt generate which seems to improve build time to ~5 minutes (max)

**Comment by krishchow** [comment]
Ah yeah, I was including installing all the dependencies as well, although I'm guessing that varies quite a bit from person to person though! I noticed that #80 will effectively address this though.

**Comment by hiimchrislim** [comment]
Yep, we're hoping that the build times will be much more improved after the refactor!
We'll definitely keep an eye out for any irregular build times! :)

Thanks again!

**Pull request merged**
