### PR TITLE
Add filtering to calendar

### PR DESCRIPTION
**Pull request by AipioxTechson**
##

NOTE: the raw github content url must be changed when pushing to master
Fixes: #172 

- [ ] Have dependencies/packages been added/removed? If so, please list them.

### Changes

Adds the ability to filter club and important dates on the calendar

### CODE REVIEW

**Review by jcserv — CHANGES_REQUESTED** [review]
Looks great, could we create a constants folder and put the relevant constants (club colours, github url, spreadsheets url) into a file there?

**Review by CometWhoosh — CHANGES_REQUESTED** [review]
The filters look great. I noticed however that the WiSC and DSC test events aren't showing up on the calendar even if the filters for them are on. I tried adding another test event for each of those clubs and didn't see them appear.

**Review by jcserv — DISMISSED** [review]

**Review by CometWhoosh — CHANGES_REQUESTED** [review]
Upon reviewing again, I noticed a few issues with the important dates events:
* It seems that, for one day events, they are displayed as two day events in the calendar. For example, September 6th is Labour day, but our event for Labour Day is on the 6th and 7th.
* If you check September 2nd, we have an event which should be named `Financial cancellation date...`. However, the event name is surrounded by quotes, so on the calendar it's `"Financial cancellation date..."`. 
* If you check October, it says that Reading week is on the 15th and 16th. However, UTM's Important Dates website lists it as taking place from the 12th to the 15th.
* When we converged long events, it seems that we didn't change the title appropriately. For example, UTM has an event from November 11th to December 7th called `Request period for Late Withdrawal (LWD) for F courses at UTM`. Our event for it is converged to be on December 7th, but the name is still `Request period for Late Withdrawal (LWD) for F courses at UTM`, even though it's the last day to request a LWD, not a the request period

**Review by CometWhoosh — APPROVED** [review]
Looks good to me! Remember to delete the test events in the club event spreadsheet before merging to master.

**Review by jcserv — APPROVED** [review]

**Review by CometWhoosh — APPROVED** [review]

**Pull request merged**
