### PR TITLE
A component to display teammates

### PR DESCRIPTION
**Pull request by milindvishnoi**
## Teammate Template

image

**Please let me know if I should make any changes in terms of design.**

I have added everyone for reviewing so you can give me advice for making the component look better if any.

### CODE REVIEW

**Comment by hiimchrislim** [comment]
Suggestion:

image
The design in the screenshot sent is pretty clean where it has an image, title, name and the points of contact.

As per the description, I propose we make it such that when a user clicks on the card, the card will "flip" and then the description would show up

**Comment by ArsalaBangash** [comment]
> Suggestion:
> 
> image
> The design in the screenshot sent is pretty clean where it has an image, title, name and the points of contact.
> 
> As per the description, I propose we make it such that when a user clicks on the card, the card will "flip" and then the description would show up. This would be somewhat similar to the resource grid where if you hover over a resource grid item, a small description of the resource will be displayed.

I agree with this suggestion.

**Comment by milindvishnoi** [comment]
## Updated Design

**Front**
image


**Back**
image

**Comment by hiimchrislim** [comment]
Looks great so far!

I have 2 comments/suggestions to make
- Is it possible if the entire card to do the flip rather than just the text?
- We should make the card only flip when a user clicks on it rather than flipping immediately on a hover. I was trying to click on the Discord icon but couldn't since the text flips when being hovered over.

**Comment by milindvishnoi** [comment]
@hiimchrislim I have made the changes you recommended.

Note: A suggestion when you ask for changes please make bulletin points it is just easier to check off all the things you completed.

**Review by hiimchrislim — APPROVED** [review]
Looks great!

**Pull request merged**
