### PR TITLE
Contributors component

### PR DESCRIPTION
**Pull request by milindvishnoi**
image

### CODE REVIEW

**Review by hiimchrislim — CHANGES_REQUESTED** [review]
Is it possible if we can scale the picture sizes based on the number of contributors?
Since there's currently only 3 contributors, it would be great if the image and text associated with it be larger

**Comment by milindvishnoi** [comment]
@hiimchrislim changing widths with no of contributors will not possible for a good design. I'll change the size for now, but you can just go change the width and height whenever u want.

**Comment by hiimchrislim** [comment]
Alright, sounds good! Great thanks!

**Comment by hiimchrislim** [comment]
Great job!

**Review by hiimchrislim — APPROVED** [review]

**Pull request merged**
